### ISSUE TITLE
Separate src/groovy from src/java files

### ISSUE THREAD

**Issue by yellowsnow** [domurtag/migrate-2-grails3#5]
Hi,

Thanks for the effort, this plugin is really helpful. 

I think there is a unwanted behavior that mixes `src/groovy` and `src/java` files in the target Grails 3 project.

Steps to reproduce :
- Fork the [shiro plugin](https://github.com/pledbrook/grails-shiro)
- Migrate the `shiro2` plugin using `migrate2-grails3:0.3.2`
- The target Grails 3 plugin/src/groovy contains a mix of Groovy and Java files

Cheers

**Comment by ghost** [comment]
According to [the docs](https://grails.org/single-page-documentation.html), files in `src/java` should be stored in `src/groovy` in a Grails 3 project, so it seems the plugin is behaving correctly
